services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: mediq
      POSTGRES_PASSWORD: mediq
      POSTGRES_DB: mediq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: